name: Build Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }} Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: snapshotter-cli-linux-x86_64
          - os: macos-latest
            asset_name: snapshotter-cli-macos-universal
          - os: windows-latest
            asset_name: snapshotter-cli-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Build Binary
        run: python build_binary.py

      - name: Rename Binary
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/snapshotter-cli.exe dist/${{ matrix.asset_name }}
          else
            mv dist/snapshotter-cli dist/${{ matrix.asset_name }}
          fi
        shell: bash

      - name: Upload Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream 