name: Build CLI Binaries

on:
  push:
    tags:
      - 'v*'
    branches:
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: amd64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: ubuntu-22.04-arm  # GitHub's native ARM64 runner
            platform: linux
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Install dependencies
      run: uv sync --frozen

    - name: Build binary with PyInstaller
      run: |
        # Set environment variables for the spec file
        export PLATFORM=${{ matrix.platform }}
        export ARCH=${{ matrix.arch }}

        # Build using the spec file
        uv run pyinstaller pyinstaller.spec \
          --distpath dist \
          --workpath build \
          --clean

    - name: Test binary
      run: |
        ./dist/powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }} --help

    - name: Create checksums
      run: |
        cd dist
        if [[ "${{ matrix.platform }}" == "macos" ]]; then
          shasum -a 256 powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }} > powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }}.sha256
        else
          sha256sum powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }} > powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }}.sha256
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          dist/powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }}
          dist/powerloom-snapshotter-cli-${{ matrix.platform }}-${{ matrix.arch }}.sha256


  release:
    needs: [build-native]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release files
      run: |
        mkdir -p release
        for artifact in artifacts/*; do
          if [[ -d "$artifact" ]]; then
            cp $artifact/* release/
          fi
        done

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        files: |
          release/*
        body: |
          ## Powerloom Snapshotter CLI Binaries

          ### Installation

          #### Linux (AMD64)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/powerloom-snapshotter-cli-linux-amd64
          chmod +x powerloom-snapshotter-cli-linux-amd64
          sudo mv powerloom-snapshotter-cli-linux-amd64 /usr/local/bin/powerloom-snapshotter-cli
          ```

          #### Linux (ARM64)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/powerloom-snapshotter-cli-linux-arm64
          chmod +x powerloom-snapshotter-cli-linux-arm64
          sudo mv powerloom-snapshotter-cli-linux-arm64 /usr/local/bin/powerloom-snapshotter-cli
          ```

          #### macOS (Apple Silicon)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/powerloom-snapshotter-cli-macos-arm64
          chmod +x powerloom-snapshotter-cli-macos-arm64
          sudo mv powerloom-snapshotter-cli-macos-arm64 /usr/local/bin/powerloom-snapshotter-cli
          ```

          ### Verify Installation
          ```bash
          powerloom-snapshotter-cli --version
          ```

          ### Checksums
          Verify the integrity of downloaded files using the provided `.sha256` files:
          ```bash
          sha256sum -c powerloom-snapshotter-cli-<platform>-<arch>.sha256
          ```
